port: "8080"
cache_dir: "./cache"
contract_address: "0x140cbDFf649929D003091a5B8B3be34588753aBA"
static_dir: "../web/dist"
rpc_urls:
  "1":
    - "https://eth.llamarpc.com"
    - "https://ethereum-rpc.publicnode.com"
  "11155111":
    - "https://ethereum-sepolia-rpc.publicnode.com"
